# Generated by Django 2.1 on 2019-04-26 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=4, verbose_name='Currency')),
            ],
            options={
                'db_table': 'fund_currency',
                'ordering': ['currency_name'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyConversion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.FloatField(verbose_name='Conversion rate')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_currency', to='funding.Currency', verbose_name='From')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_currency', to='funding.Currency', verbose_name='To')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('favorite_id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'db_table': 'fund_favorite',
                'ordering': ['funding__fundingopportunity_name'],
            },
        ),
        migrations.CreateModel(
            name='FundingOpportunity',
            fields=[
                ('fundingopportunity_id', models.AutoField(primary_key=True, serialize=False)),
                ('fundingopportunity_published', models.BooleanField(verbose_name='Published')),
                ('fundingopportunity_rolling', models.BooleanField(verbose_name='Rolling')),
                ('fundingopportunity_name', models.CharField(max_length=255, verbose_name='Fund. opportunity name')),
                ('fundingopportunity_end', models.DateTimeField(blank=True, null=True, verbose_name='Deadline (Lisbon time)')),
                ('fundingopportunity_value', models.IntegerField(blank=True, null=True, verbose_name='Funding value')),
                ('fundingopportunity_duration', models.IntegerField(blank=True, null=True, verbose_name='Duration in months')),
                ('fundingopportunity_eligibility', models.TextField(blank=True, null=True, verbose_name='Eligibility')),
                ('fundingopportunity_scope', models.TextField(blank=True, null=True, verbose_name='Scope')),
                ('fundingopportunity_brifdesc', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('fundingopportunity_desc', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('fundingopportunity_createdon', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('fundingopportunity_updatedon', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('fundingopportunity_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Link')),
                ('fundingopportunity_loideadline', models.DateTimeField(blank=True, null=True, verbose_name='LOI deadline')),
                ('fundingopportunity_fullproposal', models.DateTimeField(blank=True, null=True, verbose_name='Full proposal deadline')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.Currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name_plural': 'Funding opportunities',
                'db_table': 'fund_opportunity',
                'ordering': ['fundingopportunity_end'],
                'get_latest_by': 'fundingopportunity_end',
            },
        ),
        migrations.CreateModel(
            name='FundingType',
            fields=[
                ('fundingtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('fundingtype_name', models.CharField(max_length=255, verbose_name='Funding type')),
            ],
            options={
                'db_table': 'fund_type',
                'ordering': ['fundingtype_name'],
            },
        ),
        migrations.CreateModel(
            name='Grantor',
            fields=[
                ('grantor_id', models.AutoField(primary_key=True, serialize=False)),
                ('grantor_name', models.CharField(max_length=255, verbose_name='Funding agency')),
            ],
            options={
                'db_table': 'fund_grantor',
                'ordering': ['grantor_name'],
            },
        ),
        migrations.CreateModel(
            name='OpportunitySubject',
            fields=[
                ('opportunitysubject_id', models.AutoField(primary_key=True, serialize=False)),
                ('opportunitysubject_name', models.CharField(max_length=80, verbose_name='Type')),
                ('opportunitysubject_order', models.CharField(blank=True, max_length=2, null=True, verbose_name='Order')),
            ],
            options={
                'db_table': 'fund_subject',
                'ordering': ['opportunitysubject_name'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityTopic',
            fields=[
                ('opportunitytopic_id', models.AutoField(primary_key=True, serialize=False)),
                ('opportunitytopic_name', models.CharField(max_length=80, verbose_name='Topic')),
            ],
            options={
                'db_table': 'fund_topic',
                'ordering': ['opportunitytopic_name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentFrequency',
            fields=[
                ('paymentfrequency_id', models.AutoField(primary_key=True, serialize=False)),
                ('paymentfrequency_name', models.CharField(max_length=80, verbose_name='Payment per')),
            ],
            options={
                'db_table': 'fund_paymentfrequency',
                'ordering': ['paymentfrequency_name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('topics', models.ManyToManyField(blank=True, to='funding.OpportunityTopic', verbose_name='Topics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fund_profile',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='UserFilters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('subjects', models.ManyToManyField(blank=True, to='funding.OpportunitySubject', verbose_name='Subjects')),
                ('topics', models.ManyToManyField(blank=True, to='funding.OpportunityTopic', verbose_name='Topics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fund_usersfilters',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='fundingopportunity',
            name='financingAgency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.Grantor', verbose_name='Financing agency'),
        ),
        migrations.AddField(
            model_name='fundingopportunity',
            name='fundingtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funding.FundingType', verbose_name='Funding type'),
        ),
        migrations.AddField(
            model_name='fundingopportunity',
            name='paymentfrequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funding.PaymentFrequency', verbose_name='Payment frequency'),
        ),
        migrations.AddField(
            model_name='fundingopportunity',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.OpportunitySubject', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='fundingopportunity',
            name='topics',
            field=models.ManyToManyField(blank=True, to='funding.OpportunityTopic', verbose_name='Topics'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='funding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.FundingOpportunity'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
